openapi: 3.0.0
info:
  version: '0.0.1'
  title: 'tourdb'
  description: 'tourdb - the redesigned'
servers: 
  - url: http://localhost:8080
paths: 
  /tracks/{trkId}:
    get:
      summary: Returns a track by ID
      parameters:
        - name: trkId
          in: path
          required: true
          description: Returns a single track
          schema:
            type: integer
      responses:
        '200':
          description: Track successfully retrieved
          content:
            application/json:
              schema: {
                $ref: '#/components/schemas/tracks'
              }  
        '400':
          description: The specified track ID is invalid (e.g. not a number)
        '404':
          description: A track with the specified ID was not found
    
  

# Should this be a single object or an array? For the post method it should be a single object
components:
  schemas:
    tracks:
      type: array
      properties: 
        id:
          type: number
        name:
          type: string
        route:
          type: string
        dateBegin:
          type: string
          format: date
        dateFinish:
          type: string
          format: data
        subtype:
          type: string
        org:
          type: string
        event:
          type: string
        remarks:
          type: string
        distance:
          type: number
        startEle:
          type: number
        peakEle:
          type: number
        peakTime:
          type: string
          format: time
        lowEle:
          type: number
        lowTime:
          type: number
        finishEle:
          type: number
        grade:
          type: string
        meterUp:
          type: number
        meterDown:
          type: number
        country:
          type: string
        trkUsrId:
          type: number
        coordinates:
          type: string
        coordTop:
          type: number
        coordBottom:
          type: number
        coordLeft:
          type: number
        coordRight:
          type: number
